using System.Text;
using NebulaPanel.Application.DTOs;
using NebulaPanel.Domain.Entities;

namespace NebulaPanel.Infrastructure.OfficialGames.Minecraft.Installers;

/// <summary>
/// Creates configuration files for Minecraft servers.
/// </summary>
public static class MinecraftConfigFiles
{
    private const string EulaContent = """
        #By changing the setting below to TRUE you are indicating your agreement to our EULA (https://aka.ms/MinecraftEULA).
        #Generated by Nebula Panel
        eula=true
        """;

    /// <summary>
    /// Creates the eula.txt file with eula=true.
    /// </summary>
    /// <param name="installPath">Server installation directory.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static async Task CreateEulaAsync(
        string installPath,
        CancellationToken cancellationToken = default)
    {
        var eulaPath = Path.Combine(installPath, "eula.txt");
        await File.WriteAllTextAsync(eulaPath, EulaContent, cancellationToken)
            .ConfigureAwait(false);
    }

    /// <summary>
    /// Creates a default server.properties file if one doesn't exist.
    /// </summary>
    /// <param name="installPath">Server installation directory.</param>
    /// <param name="server">Game server entity with port configuration.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>True if file was created, false if it already existed.</returns>
    public static async Task<bool> CreateDefaultServerPropertiesAsync(
        string installPath,
        GameServer server,
        CancellationToken cancellationToken = default)
    {
        var propertiesPath = Path.Combine(installPath, "server.properties");

        // Don't overwrite existing config
        if (File.Exists(propertiesPath))
            return false;

        var rconPort = server.AdditionalPorts.GetValueOrDefault("rcon", 25575);
        var rconPassword = Guid.NewGuid().ToString("N")[..16]; // 16 char random password

        var properties = new StringBuilder();
        properties.AppendLine("#Minecraft server properties");
        properties.AppendLine($"#Generated by Nebula Panel on {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        properties.AppendLine();
        properties.AppendLine("#Server Settings");
        properties.AppendLine($"server-port={server.PrimaryPort}");
        properties.AppendLine("motd=A Nebula Panel Server");
        properties.AppendLine("max-players=20");
        properties.AppendLine("view-distance=10");
        properties.AppendLine("simulation-distance=10");
        properties.AppendLine();
        properties.AppendLine("#Gameplay");
        properties.AppendLine("gamemode=survival");
        properties.AppendLine("difficulty=normal");
        properties.AppendLine("pvp=true");
        properties.AppendLine("online-mode=true");
        properties.AppendLine();
        properties.AppendLine("#RCON - Remote Console");
        properties.AppendLine("enable-rcon=true");
        properties.AppendLine($"rcon.port={rconPort}");
        properties.AppendLine($"rcon.password={rconPassword}");
        properties.AppendLine();
        properties.AppendLine("#Query");
        properties.AppendLine("enable-query=false");
        properties.AppendLine($"query.port={server.PrimaryPort}");

        await File.WriteAllTextAsync(propertiesPath, properties.ToString(), cancellationToken)
            .ConfigureAwait(false);

        return true;
    }

    /// <summary>
    /// Creates server.properties file with wizard settings.
    /// Overwrites existing file to ensure settings are applied (e.g., after modpack install).
    /// </summary>
    public static async Task CreateServerPropertiesWithSettingsAsync(
        string installPath,
        MinecraftServerPropertiesSettings settings,
        CancellationToken cancellationToken = default)
    {
        var propertiesPath = Path.Combine(installPath, "server.properties");

        var properties = new StringBuilder();
        properties.AppendLine("#Minecraft server properties");
        properties.AppendLine($"#Generated by Nebula Panel on {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        properties.AppendLine();

        properties.AppendLine("#Server Settings");
        properties.AppendLine($"server-port={settings.Port}");
        properties.AppendLine("motd=A Nebula Panel Server");
        properties.AppendLine($"max-players={settings.MaxPlayers}");
        properties.AppendLine("view-distance=10");
        properties.AppendLine("simulation-distance=10");
        properties.AppendLine();

        properties.AppendLine("#World Settings");
        properties.AppendLine($"level-name={settings.WorldName}");
        if (!string.IsNullOrWhiteSpace(settings.WorldSeed))
            properties.AppendLine($"level-seed={settings.WorldSeed}");
        properties.AppendLine();

        properties.AppendLine("#Gameplay");
        properties.AppendLine($"gamemode={settings.GameMode.ToString().ToLowerInvariant()}");
        properties.AppendLine($"difficulty={settings.Difficulty.ToString().ToLowerInvariant()}");
        properties.AppendLine($"pvp={settings.EnablePvp.ToString().ToLowerInvariant()}");
        properties.AppendLine($"spawn-animals={settings.SpawnAnimals.ToString().ToLowerInvariant()}");
        properties.AppendLine($"spawn-monsters={settings.SpawnMonsters.ToString().ToLowerInvariant()}");
        properties.AppendLine($"enable-command-block={settings.EnableCommandBlocks.ToString().ToLowerInvariant()}");
        properties.AppendLine("online-mode=true");
        properties.AppendLine();

        properties.AppendLine("#RCON - Remote Console");
        properties.AppendLine($"enable-rcon={settings.EnableRcon.ToString().ToLowerInvariant()}");
        properties.AppendLine($"rcon.port={settings.RconPort}");
        if (settings.EnableRcon && !string.IsNullOrEmpty(settings.RconPassword))
            properties.AppendLine($"rcon.password={settings.RconPassword}");
        properties.AppendLine();

        properties.AppendLine("#Query");
        properties.AppendLine("enable-query=false");
        properties.AppendLine($"query.port={settings.Port}");

        await File.WriteAllTextAsync(propertiesPath, properties.ToString(), cancellationToken)
            .ConfigureAwait(false);
    }

    /// <summary>
    /// Creates a user_jvm_args.txt file for modern Forge servers.
    /// </summary>
    /// <param name="installPath">Server installation directory.</param>
    /// <param name="jvmArgs">JVM arguments to include.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static async Task CreateForgeJvmArgsAsync(
        string installPath,
        string jvmArgs,
        CancellationToken cancellationToken = default)
    {
        var argsPath = Path.Combine(installPath, "user_jvm_args.txt");

        // Don't overwrite if exists
        if (File.Exists(argsPath))
            return;

        var content = $"""
            # Xmx and Xms set the maximum and minimum RAM usage, respectively.
            # They can take any number, followed by an M or G for megabytes or gigabytes.
            # Generated by Nebula Panel
            {jvmArgs}
            """;

        await File.WriteAllTextAsync(argsPath, content, cancellationToken)
            .ConfigureAwait(false);
    }
}
