// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NebulaPanel.Infrastructure.Persistence;

#nullable disable

namespace NebulaPanel.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NebulaPanelDbContext))]
    [Migration("20260120120000_AddGameServerRowVersion")]
    partial class AddGameServerRowVersion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("NebulaPanel.Domain.Entities.Announcement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_user_id");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPinned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_pinned");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_announcements");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_announcements_created_by_user_id");

                    b.HasIndex("DisplayOrder")
                        .HasDatabaseName("ix_announcements_display_order");

                    b.HasIndex("IsActive", "ExpiresAt")
                        .HasDatabaseName("ix_announcements_is_active_expires_at");

                    b.ToTable("announcements");
                });

            modelBuilder.Entity("NebulaPanel.Domain.Entities.Backup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("file_path");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_size_bytes");

                    b.Property<bool>("IncludesConfig")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("includes_config");

                    b.Property<bool>("IncludesMods")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("includes_mods");

                    b.Property<bool>("IncludesWorld")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("includes_world");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<Guid?>("ScheduledTaskId")
                        .HasColumnType("TEXT")
                        .HasColumnName("scheduled_task_id");

                    b.Property<int>("Scope")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("scope");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("server_id");

                    b.Property<string>("SourcePaths")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_paths");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_backups");

                    b.HasIndex("ServerId")
                        .HasDatabaseName("ix_backups_server_id");

                    b.HasIndex("ServerId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_backups_server_id_created_at");

                    b.ToTable("backups");
                });

            modelBuilder.Entity("NebulaPanel.Domain.Entities.GameServer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AdditionalPorts")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("additional_ports");

                    b.Property<string>("BindAddress")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("0.0.0.0")
                        .HasColumnName("bind_address");

                    b.Property<int>("DeploymentType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deployment_type");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("DockerConfig")
                        .HasColumnType("TEXT")
                        .HasColumnName("docker_config");

                    b.Property<string>("DockerContainerId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("docker_container_id");

                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT")
                        .HasColumnName("game_id");

                    b.Property<string>("HytaleInfo")
                        .HasColumnType("TEXT")
                        .HasColumnName("hytale_info");

                    b.Property<string>("IconPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("icon_path");

                    b.Property<string>("InstallPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("install_path");

                    b.Property<string>("InstalledModpack")
                        .HasColumnType("TEXT")
                        .HasColumnName("installed_modpack");

                    b.Property<string>("InstalledVersion")
                        .HasColumnType("TEXT")
                        .HasColumnName("installed_version");

                    b.Property<DateTime?>("LastStarted")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_started");

                    b.Property<DateTime?>("LastStopped")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_stopped");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("NativeConfig")
                        .HasColumnType("TEXT")
                        .HasColumnName("native_config");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("owner_id");

                    b.Property<int>("PrimaryPort")
                        .HasColumnType("INTEGER")
                        .HasColumnName("primary_port");

                    b.Property<int?>("ProcessId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("process_id");

                    b.Property<string>("RconConfig")
                        .HasColumnType("TEXT")
                        .HasColumnName("rcon_config");

                    b.Property<string>("ResourceLimits")
                        .HasColumnType("TEXT")
                        .HasColumnName("resource_limits");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB")
                        .HasColumnName("row_version");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_game_servers");

                    b.HasIndex("DeploymentType")
                        .HasDatabaseName("ix_game_servers_deployment_type");

                    b.HasIndex("GameId")
                        .HasDatabaseName("ix_game_servers_game_id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_game_servers_owner_id");

                    b.HasIndex("OwnerId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_game_servers_owner_id_name");

                    b.ToTable("game_servers");
                });

            // Note: This is a partial designer file containing only GameServer entity.
            // For a complete migration, this would include all entities from the model snapshot.
            // The migration itself only adds the RowVersion column to game_servers table.
#pragma warning restore 612, 618
        }
    }
}
