// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NebulaPanel.Infrastructure.Persistence;

#nullable disable

namespace NebulaPanel.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NebulaPanelDbContext))]
    [Migration("20260108221641_AddRefreshTokens")]
    partial class AddRefreshTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("NebulaPanel.Domain.Entities.Backup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("file_path");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_size_bytes");

                    b.Property<bool>("IncludesConfig")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("includes_config");

                    b.Property<bool>("IncludesMods")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("includes_mods");

                    b.Property<bool>("IncludesWorld")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("includes_world");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("server_id");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_backups");

                    b.HasIndex("ServerId")
                        .HasDatabaseName("ix_backups_server_id");

                    b.ToTable("backups");
                });

            modelBuilder.Entity("NebulaPanel.Domain.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ConfigurationSchemas")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("configuration_schemas");

                    b.Property<string>("DefaultDockerImage")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("default_docker_image");

                    b.Property<string>("DefaultExecutablePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("default_executable_path");

                    b.Property<string>("DefaultStartCommand")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("default_start_command");

                    b.Property<string>("DefaultStopCommand")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("default_stop_command");

                    b.Property<int>("ExecutableType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("executable_type");

                    b.Property<string>("IconPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("icon_path");

                    b.Property<string>("ModProviders")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("mod_providers");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("RconDefaults")
                        .HasColumnType("TEXT")
                        .HasColumnName("rcon_defaults");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("slug");

                    b.Property<string>("SteamAppId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("steam_app_id");

                    b.Property<bool>("SupportsDocker")
                        .HasColumnType("INTEGER")
                        .HasColumnName("supports_docker");

                    b.Property<bool>("SupportsMods")
                        .HasColumnType("INTEGER")
                        .HasColumnName("supports_mods");

                    b.HasKey("Id")
                        .HasName("pk_games");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_games_slug");

                    b.ToTable("games");
                });

            modelBuilder.Entity("NebulaPanel.Domain.Entities.GameServer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AdditionalPorts")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("additional_ports");

                    b.Property<string>("BindAddress")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("0.0.0.0")
                        .HasColumnName("bind_address");

                    b.Property<int>("DeploymentType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deployment_type");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("DockerConfig")
                        .HasColumnType("TEXT")
                        .HasColumnName("docker_config");

                    b.Property<string>("DockerContainerId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("docker_container_id");

                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT")
                        .HasColumnName("game_id");

                    b.Property<string>("InstallPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("install_path");

                    b.Property<DateTime?>("LastStarted")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_started");

                    b.Property<DateTime?>("LastStopped")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_stopped");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("NativeConfig")
                        .HasColumnType("TEXT")
                        .HasColumnName("native_config");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("owner_id");

                    b.Property<int>("PrimaryPort")
                        .HasColumnType("INTEGER")
                        .HasColumnName("primary_port");

                    b.Property<int?>("ProcessId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("process_id");

                    b.Property<string>("RconConfig")
                        .HasColumnType("TEXT")
                        .HasColumnName("rcon_config");

                    b.Property<string>("ResourceLimits")
                        .HasColumnType("TEXT")
                        .HasColumnName("resource_limits");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_game_servers");

                    b.HasIndex("DeploymentType")
                        .HasDatabaseName("ix_game_servers_deployment_type");

                    b.HasIndex("GameId")
                        .HasDatabaseName("ix_game_servers_game_id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_game_servers_owner_id");

                    b.HasIndex("OwnerId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_game_servers_owner_id_name");

                    b.ToTable("game_servers");
                });

            modelBuilder.Entity("NebulaPanel.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_permissions_code");

                    b.ToTable("permissions");
                });

            modelBuilder.Entity("NebulaPanel.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("replaced_by_token");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens");
                });

            modelBuilder.Entity("NebulaPanel.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("IsSystemRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system_role");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("priority");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_name");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("NebulaPanel.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_role_permissions");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_role_permissions_permission_id");

                    b.ToTable("role_permissions");
                });

            modelBuilder.Entity("NebulaPanel.Domain.Entities.ScheduledTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Configuration")
                        .HasColumnType("TEXT")
                        .HasColumnName("configuration");

                    b.Property<string>("CronExpression")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("cron_expression");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<DateTime?>("LastRunAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_run_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateTime?>("NextRunAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("next_run_at");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("server_id");

                    b.Property<int>("TaskType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("task_type");

                    b.HasKey("Id")
                        .HasName("pk_scheduled_tasks");

                    b.HasIndex("ServerId")
                        .HasDatabaseName("ix_scheduled_tasks_server_id");

                    b.ToTable("scheduled_tasks");
                });

            modelBuilder.Entity("NebulaPanel.Domain.Entities.ServerMod", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("FileHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("file_hash");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_size_bytes");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("icon_url");

                    b.Property<DateTime>("InstalledAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("installed_at");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<string>("LocalPath")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("local_path");

                    b.Property<string>("ModId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("mod_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER")
                        .HasColumnName("provider");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("server_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Version")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("version");

                    b.Property<string>("VersionId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("version_id");

                    b.HasKey("Id")
                        .HasName("pk_server_mods");

                    b.HasIndex("ServerId")
                        .HasDatabaseName("ix_server_mods_server_id");

                    b.HasIndex("ServerId", "Provider", "ModId")
                        .IsUnique()
                        .HasDatabaseName("ix_server_mods_server_id_provider_mod_id");

                    b.ToTable("server_mods");
                });

            modelBuilder.Entity("NebulaPanel.Domain.Entities.ServerPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("IsGranted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_granted");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("permission_code");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("server_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_server_permissions");

                    b.HasIndex("ServerId")
                        .HasDatabaseName("ix_server_permissions_server_id");

                    b.HasIndex("UserId", "ServerId", "PermissionCode")
                        .IsUnique()
                        .HasDatabaseName("ix_server_permissions_user_id_server_id_permission_code");

                    b.ToTable("server_permissions");
                });

            modelBuilder.Entity("NebulaPanel.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users");
                });

            modelBuilder.Entity("NebulaPanel.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("assigned_at");

                    b.Property<Guid?>("AssignedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("assigned_by");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles");
                });

            modelBuilder.Entity("NebulaPanel.Domain.Entities.Backup", b =>
                {
                    b.HasOne("NebulaPanel.Domain.Entities.GameServer", "Server")
                        .WithMany("Backups")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_backups_game_servers_server_id");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("NebulaPanel.Domain.Entities.GameServer", b =>
                {
                    b.HasOne("NebulaPanel.Domain.Entities.Game", "Game")
                        .WithMany("Servers")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_game_servers_games_game_id");

                    b.HasOne("NebulaPanel.Domain.Entities.User", "Owner")
                        .WithMany("OwnedServers")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_game_servers_users_owner_id");

                    b.Navigation("Game");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("NebulaPanel.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("NebulaPanel.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NebulaPanel.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("NebulaPanel.Domain.Entities.Permission", "Permission")
                        .WithMany("Roles")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_id");

                    b.HasOne("NebulaPanel.Domain.Entities.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_id");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("NebulaPanel.Domain.Entities.ScheduledTask", b =>
                {
                    b.HasOne("NebulaPanel.Domain.Entities.GameServer", "Server")
                        .WithMany("ScheduledTasks")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scheduled_tasks_game_servers_server_id");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("NebulaPanel.Domain.Entities.ServerMod", b =>
                {
                    b.HasOne("NebulaPanel.Domain.Entities.GameServer", "Server")
                        .WithMany("InstalledMods")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_server_mods_game_servers_server_id");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("NebulaPanel.Domain.Entities.ServerPermission", b =>
                {
                    b.HasOne("NebulaPanel.Domain.Entities.GameServer", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_server_permissions_game_servers_server_id");

                    b.HasOne("NebulaPanel.Domain.Entities.User", "User")
                        .WithMany("ServerPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_server_permissions_users_user_id");

                    b.Navigation("Server");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NebulaPanel.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("NebulaPanel.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("NebulaPanel.Domain.Entities.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NebulaPanel.Domain.Entities.Game", b =>
                {
                    b.Navigation("Servers");
                });

            modelBuilder.Entity("NebulaPanel.Domain.Entities.GameServer", b =>
                {
                    b.Navigation("Backups");

                    b.Navigation("InstalledMods");

                    b.Navigation("ScheduledTasks");
                });

            modelBuilder.Entity("NebulaPanel.Domain.Entities.Permission", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("NebulaPanel.Domain.Entities.Role", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("NebulaPanel.Domain.Entities.User", b =>
                {
                    b.Navigation("OwnedServers");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Roles");

                    b.Navigation("ServerPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
