using NebulaPanel.Domain.Enums;
using NebulaPanel.Domain.ValueObjects;

namespace NebulaPanel.Infrastructure.OfficialGames.FikaHeadless;

/// <summary>
/// Partial class containing the Docker environment variable configuration schema for Fika Headless Client.
/// </summary>
public partial class FikaHeadlessProvider
{
    static partial void AddDockerEnvSchema(Dictionary<string, ConfigurationSchema> schemas)
    {
        schemas["docker-env"] = new ConfigurationSchema
        {
            FileName = "docker-env",
            DisplayName = "Docker Environment",
            Description = "Docker container environment variables for Fika Headless Client",
            FileType = ConfigFileType.Properties,
            CreateIfMissing = false,
            Sections =
            [
                new ConfigSection
                {
                    Key = "Core",
                    DisplayName = "Core Settings",
                    Description = "Essential headless client connection settings",
                    Icon = "server",
                    Order = 1,
                    DefaultExpanded = true
                },
                new ConfigSection
                {
                    Key = "Performance",
                    DisplayName = "Performance & Behavior",
                    Description = "Wine compatibility, restart behavior, and debug options",
                    Icon = "cog",
                    Order = 2,
                    DefaultExpanded = false
                }
            ],
            Fields =
            [
                // =====================
                // CORE SETTINGS
                // =====================
                new ConfigField
                {
                    Key = "PROFILE_ID",
                    DisplayName = "Profile ID",
                    Description = "The headless profile ID to use. Generated by the parent Fika SPT server when NUM_HEADLESS_PROFILES > 0.",
                    Type = ConfigFieldType.String,
                    DefaultValue = "",
                    Category = "Core",
                    Order = 1,
                    Required = true,
                    Placeholder = "e.g., 67890abcdef1234567890abc"
                },
                new ConfigField
                {
                    Key = "SERVER_URL",
                    DisplayName = "Server URL",
                    Description = "URL of the parent Fika SPT server that this headless client connects to.",
                    Type = ConfigFieldType.String,
                    DefaultValue = "",
                    Category = "Core",
                    Order = 2,
                    Required = true,
                    Placeholder = "e.g., https://fika-spt:6969"
                },
                new ConfigField
                {
                    Key = "SERVER_PORT",
                    DisplayName = "Server Port",
                    Description = "Port of the parent Fika SPT server.",
                    Type = ConfigFieldType.Port,
                    DefaultValue = 6969,
                    Category = "Core",
                    Order = 3,
                    Required = true
                },

                // =====================
                // PERFORMANCE SETTINGS
                // =====================
                new ConfigField
                {
                    Key = "HTTPS",
                    DisplayName = "Use HTTPS",
                    Description = "Use HTTPS to connect to the parent server. Required for SPT >= 3.11.",
                    Type = ConfigFieldType.Bool,
                    DefaultValue = true,
                    Category = "Performance",
                    Order = 1
                },
                new ConfigField
                {
                    Key = "ESYNC",
                    DisplayName = "Wine Esync",
                    Description = "Enable Wine esync for improved performance.",
                    Type = ConfigFieldType.Bool,
                    DefaultValue = true,
                    Category = "Performance",
                    Order = 2
                },
                new ConfigField
                {
                    Key = "FSYNC",
                    DisplayName = "Wine Fsync",
                    Description = "Enable Wine fsync for improved performance.",
                    Type = ConfigFieldType.Bool,
                    DefaultValue = true,
                    Category = "Performance",
                    Order = 3
                },
                new ConfigField
                {
                    Key = "NTSYNC",
                    DisplayName = "Wine NTSync",
                    Description = "Enable Wine ntsync (experimental, requires kernel support).",
                    Type = ConfigFieldType.Bool,
                    DefaultValue = false,
                    Category = "Performance",
                    Order = 4
                },
                new ConfigField
                {
                    Key = "AUTO_RESTART_ON_RAID_END",
                    DisplayName = "Auto-Restart on Raid End",
                    Description = "Automatically restart the headless client after each raid ends. Helps with memory management.",
                    Type = ConfigFieldType.Bool,
                    DefaultValue = true,
                    Category = "Performance",
                    Order = 5
                },
                new ConfigField
                {
                    Key = "ENABLE_LOG_PURGE",
                    DisplayName = "Enable Log Purge",
                    Description = "Purge old log files to save disk space.",
                    Type = ConfigFieldType.Bool,
                    DefaultValue = true,
                    Category = "Performance",
                    Order = 6
                },
                new ConfigField
                {
                    Key = "USE_MODSYNC",
                    DisplayName = "Use ModSync",
                    Description = "Sync mods from the parent server via Corter-ModSync plugin.",
                    Type = ConfigFieldType.Bool,
                    DefaultValue = false,
                    Category = "Performance",
                    Order = 7
                },
                new ConfigField
                {
                    Key = "DISABLE_NODYNAMICAI",
                    DisplayName = "Disable NoDynamicAI",
                    Description = "Disable the NoDynamicAI feature.",
                    Type = ConfigFieldType.Bool,
                    DefaultValue = false,
                    Category = "Performance",
                    Order = 8
                },
                new ConfigField
                {
                    Key = "SAVE_LOG_ON_EXIT",
                    DisplayName = "Save Log on Exit",
                    Description = "Save the BepInEx log when the client exits. Useful for debugging.",
                    Type = ConfigFieldType.Bool,
                    DefaultValue = false,
                    Category = "Performance",
                    Order = 9,
                    Advanced = true
                },
                new ConfigField
                {
                    Key = "XVFB_DEBUG",
                    DisplayName = "Xvfb Debug",
                    Description = "Enable Xvfb debug output. Useful for troubleshooting display issues.",
                    Type = ConfigFieldType.Bool,
                    DefaultValue = false,
                    Category = "Performance",
                    Order = 10,
                    Advanced = true
                },
                new ConfigField
                {
                    Key = "USE_DGPU",
                    DisplayName = "Use Discrete GPU",
                    Description = "Use a discrete GPU if available. May improve performance for some setups.",
                    Type = ConfigFieldType.Bool,
                    DefaultValue = false,
                    Category = "Performance",
                    Order = 11,
                    Advanced = true
                }
            ]
        };
    }
}
