using System.Text;
using Microsoft.Extensions.Logging;
using NebulaPanel.Application.DTOs;
using NebulaPanel.Domain.Entities;
using NebulaPanel.Domain.Enums;
using NebulaPanel.Infrastructure.OfficialGames.Minecraft.Models;

namespace NebulaPanel.Infrastructure.ModpackProviders;

/// <summary>
/// Handles post-installation server configuration for modpacks.
/// Creates EULA, start scripts, and server.properties.
/// </summary>
public class ModpackServerConfigurator(ILogger<ModpackServerConfigurator> logger)
{
    private readonly ILogger<ModpackServerConfigurator> _logger = logger;

    /// <summary>
    /// Configures the server after modpack installation.
    /// </summary>
    public async Task ConfigureAsync(
        GameServer server,
        ModpackInstallRequest request,
        StartupCommandInfo? startupCommand,
        CancellationToken ct = default)
    {
        var serverPath = server.InstallPath;

        _logger.LogInformation("Configuring server at {Path}", serverPath);

        // Create EULA file
        await CreateEulaFileAsync(serverPath, ct).ConfigureAwait(false);

        // Create start script
        var ramMb = request.RecommendedRamMb ?? 4096;
        await CreateStartScriptAsync(serverPath, ramMb, request.Loader, startupCommand, ct).ConfigureAwait(false);

        // Configure server.properties if it doesn't exist
        await ConfigureServerPropertiesAsync(server, ct).ConfigureAwait(false);

        _logger.LogInformation("Server configuration completed");
    }

    /// <summary>
    /// Creates the eula.txt file with eula=true.
    /// </summary>
    public async Task CreateEulaFileAsync(string serverPath, CancellationToken ct = default)
    {
        var eulaPath = Path.Combine(serverPath, "eula.txt");

        // Don't overwrite if exists and already accepted
        if (File.Exists(eulaPath))
        {
            var content = await File.ReadAllTextAsync(eulaPath, ct).ConfigureAwait(false);
            if (content.Contains("eula=true", StringComparison.OrdinalIgnoreCase))
            {
                _logger.LogDebug("EULA already accepted");
                return;
            }
        }

        var eulaContent = """
            #By changing the setting below to TRUE you are indicating your agreement to our EULA (https://aka.ms/MinecraftEULA).
            #Generated by Nebula Panel
            eula=true
            """;

        await File.WriteAllTextAsync(eulaPath, eulaContent, ct).ConfigureAwait(false);
        _logger.LogDebug("Created eula.txt");
    }

    /// <summary>
    /// Creates the appropriate start script for the server.
    /// </summary>
    public async Task CreateStartScriptAsync(
        string serverPath,
        long ramMb,
        ModLoaderType loader,
        StartupCommandInfo? startupCommand,
        CancellationToken ct = default)
    {
        var isWindows = OperatingSystem.IsWindows();
        var scriptName = isWindows ? "start.bat" : "start.sh";
        var scriptPath = Path.Combine(serverPath, scriptName);

        // Don't overwrite existing script
        if (File.Exists(scriptPath))
        {
            _logger.LogDebug("Start script already exists");
            return;
        }

        var script = new StringBuilder();

        if (isWindows)
        {
            script.AppendLine("@echo off");
            script.AppendLine(":: Minecraft Server Start Script - Generated by Nebula Panel");
            script.AppendLine();
        }
        else
        {
            script.AppendLine("#!/bin/bash");
            script.AppendLine("# Minecraft Server Start Script - Generated by Nebula Panel");
            script.AppendLine();
        }

        // Build Java command
        var javaCommand = BuildJavaCommand(ramMb, loader, startupCommand);
        script.AppendLine(javaCommand);

        if (isWindows)
        {
            script.AppendLine();
            script.AppendLine("pause");
        }

        await File.WriteAllTextAsync(scriptPath, script.ToString(), ct).ConfigureAwait(false);

        // Make script executable on Linux/macOS
        if (!isWindows)
        {
            try
            {
                var chmod = new System.Diagnostics.Process
                {
                    StartInfo = new System.Diagnostics.ProcessStartInfo
                    {
                        FileName = "chmod",
                        Arguments = $"+x \"{scriptPath}\"",
                        UseShellExecute = false,
                        CreateNoWindow = true
                    }
                };
                chmod.Start();
                await chmod.WaitForExitAsync(ct).ConfigureAwait(false);
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "Failed to make start script executable");
            }
        }

        _logger.LogDebug("Created start script: {Script}", scriptName);
    }

    /// <summary>
    /// Configures server.properties with default values if it doesn't exist.
    /// </summary>
    public async Task ConfigureServerPropertiesAsync(GameServer server, CancellationToken ct = default)
    {
        var propertiesPath = Path.Combine(server.InstallPath, "server.properties");

        // Don't overwrite existing config
        if (File.Exists(propertiesPath))
        {
            _logger.LogDebug("server.properties already exists");
            return;
        }

        var rconPort = server.AdditionalPorts.GetValueOrDefault("rcon", 25575);
        var rconPassword = Guid.NewGuid().ToString("N")[..16];

        var properties = new StringBuilder();
        properties.AppendLine("#Minecraft server properties");
        properties.AppendLine($"#Generated by Nebula Panel on {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        properties.AppendLine();
        properties.AppendLine("#Server Settings");
        properties.AppendLine($"server-port={server.PrimaryPort}");
        properties.AppendLine("motd=A Nebula Panel Modpack Server");
        properties.AppendLine("max-players=20");
        properties.AppendLine("view-distance=10");
        properties.AppendLine("simulation-distance=10");
        properties.AppendLine();
        properties.AppendLine("#Gameplay");
        properties.AppendLine("gamemode=survival");
        properties.AppendLine("difficulty=normal");
        properties.AppendLine("pvp=true");
        properties.AppendLine("online-mode=true");
        properties.AppendLine();
        properties.AppendLine("#RCON - Remote Console");
        properties.AppendLine("enable-rcon=true");
        properties.AppendLine($"rcon.port={rconPort}");
        properties.AppendLine($"rcon.password={rconPassword}");
        properties.AppendLine();
        properties.AppendLine("#Query");
        properties.AppendLine("enable-query=false");
        properties.AppendLine($"query.port={server.PrimaryPort}");

        await File.WriteAllTextAsync(propertiesPath, properties.ToString(), ct).ConfigureAwait(false);
        _logger.LogDebug("Created server.properties");
    }

    /// <summary>
    /// Creates user_jvm_args.txt for Forge/NeoForge servers.
    /// </summary>
    public async Task CreateJvmArgsFileAsync(string serverPath, long ramMb, CancellationToken ct = default)
    {
        var argsPath = Path.Combine(serverPath, "user_jvm_args.txt");

        // Don't overwrite if exists
        if (File.Exists(argsPath))
        {
            _logger.LogDebug("user_jvm_args.txt already exists");
            return;
        }

        var content = $"""
            # Xmx and Xms set the maximum and minimum RAM usage, respectively.
            # They can take any number, followed by an M or G for megabytes or gigabytes.
            # Generated by Nebula Panel
            -Xmx{ramMb}M -Xms{Math.Min(ramMb, 2048)}M
            """;

        await File.WriteAllTextAsync(argsPath, content, ct).ConfigureAwait(false);
        _logger.LogDebug("Created user_jvm_args.txt");
    }

    /// <summary>
    /// Builds the Java command for starting the server.
    /// </summary>
    private static string BuildJavaCommand(long ramMb, ModLoaderType loader, StartupCommandInfo? startupCommand)
    {
        var cmd = new StringBuilder("java ");

        // Add memory settings
        cmd.Append($"-Xmx{ramMb}M -Xms{Math.Min(ramMb, 2048)}M ");

        // Add common optimization flags
        cmd.Append("-XX:+UseG1GC ");
        cmd.Append("-XX:+ParallelRefProcEnabled ");
        cmd.Append("-XX:MaxGCPauseMillis=200 ");

        // If we have startup command info from the loader installer
        if (startupCommand is not null)
        {
            if (startupCommand.UseArgsFile)
            {
                // Modern Forge/NeoForge style - uses args files
                cmd.Append(startupCommand.Arguments);
            }
            else if (!string.IsNullOrEmpty(startupCommand.ExecutablePath))
            {
                // Traditional jar execution
                cmd.Append($"-jar \"{startupCommand.ExecutablePath}\" ");
                cmd.Append(startupCommand.Arguments);
            }
        }
        else
        {
            // Fallback based on loader type
            var jarName = loader switch
            {
                ModLoaderType.Fabric => "fabric-server-launch.jar",
                ModLoaderType.Quilt => "quilt-server-launch.jar",
                ModLoaderType.Forge => "server.jar", // Legacy fallback
                ModLoaderType.NeoForge => "server.jar", // Legacy fallback
                _ => "server.jar"
            };

            cmd.Append($"-jar \"{jarName}\" nogui");
        }

        return cmd.ToString();
    }
}
